export const SETTINGS_STATE_EVENTS = {
  UPDATED_LANGUAGE: Symbol('UPDATED_LANGUAGE'),
  UPDATED_AUTOSAVE_INTERVAL: Symbol('UPDATED_AUTOSAVE_INTERVAL'),
  UPDATED_UPDATE_INTERVAL: Symbol('UPDATED_UPDATE_INTERVAL'),
};
