export const MAINFRAME_DEVELOPING_PROGRAMS_STATE_UI_EVENTS = {
  DEVELOPING_PROGRAMS_UPDATED: Symbol('DEVELOPING_PROGRAMS_UPDATED'),
  DEVELOPING_PROGRAM_UPDATED: Symbol('DEVELOPING_PROGRAM_UPDATED'),
  DEVELOPING_PROGRAM_PROGRESS_UPDATED: Symbol('DEVELOPING_PROGRAM_PROGRESS_UPDATED'),
};
