export const MAINFRAME_PROCESSES_STATE_UI_EVENTS = {
  PROCESSES_UPDATED: Symbol('PROCESSES_UPDATED'),
  PROCESS_UPDATED: Symbol('PROCESS_UPDATED'),
  AVAILABLE_RAM_UPDATED: Symbol('AVAILABLE_RAM_UPDATED'),
  AVAILABLE_CORES_UPDATED: Symbol('AVAILABLE_CORES_UPDATED'),
};
