export const COMPANY_CLONES_STATE_UI_EVENTS = {
  CLONES_UPDATED: Symbol('CLONES_UPDATED'),
  EXPERIENCE_MODIFIERS_UPDATED: Symbol('EXPERIENCE_MODIFIERS_UPDATED'),
  EXTRA_EXPERIENCE_UPDATED: Symbol('EXTRA_EXPERIENCE_UPDATED'),
};
