export const GLOBAL_STATE_UI_EVENTS = {
  MONEY_CHANGED: Symbol('MONEY_CHANGED'),
  MONEY_INCREASED: Symbol('MONEY_INCREASED'),
  MONEY_SPENT: Symbol('MONEY_SPENT'),
  GAME_TIME_CHANGED: Symbol('GAME_TIME_CHANGED'),
  ACCUMULATED_TIME_CHANGED: Symbol('ACCUMULATED_TIME_CHANGED'),
  DEVELOPMENT_POINTS_CHANGED: Symbol('DEVELOPMENT_POINTS_CHANGED'),
  DEVELOPMENT_LEVEL_CHANGED: Symbol('DEVELOPMENT_LEVEL_CHANGED'),
  POINTS_BY_PROGRAM_CHANGED: Symbol('POINTS_BY_PROGRAM_CHANGED'),
  MULTIPLIER_CHANGED: Symbol('MULTIPLIER_CHANGED'),
  FEATURE_UNLOCKED: Symbol('FEATURE_UNLOCKED'),
};
