export const GLOBAL_STATE_UI_EVENTS = {
  MONEY_CHANGED: Symbol('MONEY_CHANGED'),
  MONEY_INCREASED: Symbol('MONEY_INCREASED'),
  MONEY_SPENT: Symbol('MONEY_SPENT'),
  OFFLINE_TIME_CHANGED: Symbol('OFFLINE_TIME_CHANGED'),
  CITY_DEVELOPMENT_POINTS_UPDATED: Symbol('CITY_DEVELOPMENT_POINTS_UPDATED'),
  CITY_DEVELOPMENT_LEVEL_UPDATED: Symbol('CITY_DEVELOPMENT_LEVEL_UPDATED'),
};
