export const MAINFRAME_PROCESSES_STATE_UI_EVENTS = {
  PROCESSES_UPDATED: Symbol('PROCESSES_UPDATED'),
  PROCESS_UPDATED: Symbol('PROCESS_UPDATED'),
  PROCESS_PROGRESS_UPDATED: Symbol('PROCESS_PROGRESS_UPDATED'),
};

export const MAINFRAME_PROCESSES_STATE_EVENTS = {
  PROCESS_TOGGLED: Symbol('PROCESS_TOGGLED'),
  PROCESS_PROGRAM_UPDATED: Symbol('PROCESS_PROGRAM_UPDATED'),
};
