export const TYPES = {
  App: Symbol('App'),
  AppState: Symbol('AppState'),
  ScenarioState: Symbol('ScenarioState'),
  GeneralState: Symbol('GeneralState'),
  CityState: Symbol('CityState'),
  SettingsState: Symbol('SettingsState'),
  MessageLogState: Symbol('MessageLogState'),
  MainframeHardwareState: Symbol('MainframeHardwareState'),
  MainframeOwnedProgramsState: Symbol('MainframeOwnedProgramsState'),
  MainframeProcessesState: Symbol('MainframeProcessesState'),
  MainframeDevelopingProgramsState: Symbol('MainframeDevelopingProgramsState'),
  ProgramFactory: Symbol('ProgramFactory'),
  Formatter: Symbol('Formatter'),
};
