export const TYPES = {
  App: Symbol('App'),
  AppState: Symbol('AppState'),
  ScenarioState: Symbol('ScenarioState'),
  GlobalState: Symbol('GlobalState'),
  CityState: Symbol('CityState'),
  SettingsState: Symbol('SettingsState'),
  MessageLogState: Symbol('MessageLogState'),
  MainframeHardwareState: Symbol('MainframeHardwareState'),
  MainframeProgramsState: Symbol('MainframeProgramsState'),
  MainframeProcessesState: Symbol('MainframeProcessesState'),
  ProgramFactory: Symbol('ProgramFactory'),
  MainframeHardwareAutomationState: Symbol('MainframeHardwareAutomationState'),
  MainframeProgramsAutomationState: Symbol('MainframeProgramsAutomationState'),
  Formatter: Symbol('Formatter'),
};
