export const GROWTH_STATE_UI_EVENTS = {
  MONEY_GROWTH_CHANGED: Symbol('MONEY_GROWTH_CHANGED'),
  DEVELOPMENT_GROWTH_CHANGED: Symbol('DEVELOPMENT_GROWTH_CHANGED'),
  CODE_BASE_GROWTH_CHANGED: Symbol('CODE_BASE_GROWTH_CHANGED'),
  PROGRAM_COMPLETION_SPEED_CHANGED: Symbol('PROGRAM_COMPLETION_SPEED_CHANGED'),
};
